In [13]:
# Function Example

def greet():
    print("Welcome to Python")

greet()

Welcome to Python


In [14]:
# If Statement Example

age = 18

if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")

You are eligible to vote.


In [15]:
# For Loop Example

for i in range(1, 6):
    print(i)

1
2
3
4
5


In [16]:
# Method Example (String Method)

text = "python"

print("Original:", text)
print("Upper:", text.upper())

Original: python
Upper: PYTHON


In [17]:
# List Method Example

numbers = [10, 20, 30]

print("Original:", numbers)

numbers.append(40)

print("After append:", numbers)

Original: [10, 20, 30]
After append: [10, 20, 30, 40]


In [18]:
list_1=[]
for i in range(10):
  list_1.append(i)
  list_1.append(i+1)
print(list_1)
print(list_1[1])

[0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10]
1

n=int(input("enter the number:"))
for i in range(2,7):
  print(i*n)

[0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10]
1
enter the number:2
4
6
8
10
12


In [19]:
count=0
while count<5:
  print(count)
  count+=1

0
1
2
3
4


In [23]:
user_input=''
while user_input .lower() != 'quit' :
  user_input=input("enter something to stop:")
print("you entered:",user_input)

enter something to stop:quit
you entered: quit


In [24]:
def find_square(num):
  result=num*num
  return result
square=find_square(5)
print("Square :-",square)

Square :- 25


In [25]:
def sum_of_digits(n):
    total = 0

    while n > 0:
        digit = n % 10
        total = total + digit
        n = n // 10

    return total


num = int(input("Enter a number: "))
print("Sum of digits =", sum_of_digits(num))

Enter a number: 12
Sum of digits = 3


In [26]:
square = lambda x: x * x
print(square(5))
#Map
number=[2,3,4,5]
mul=list(map(lambda x:x*2,number))
print("map method:-",mul)

25
map method:- [4, 6, 8, 10]


In [ ]:
print(filter)
print(type(filter))


<class 'filter'>
<class 'type'>


In [27]:
numbers = [2, 3, 4, 5, 6, 7, 8, 9, 10]

even_numbers = list(filter(lambda x: x % 2 == 0, numbers))

print(even_numbers)

[2, 4, 6, 8, 10]


In [28]:
import numpy as np

d_0 = np.array(42)

d_1 = np.array([42, 44, 46, 48])

d_2 = np.array([
    [1, 2, 3],
    ['t', 'u', 'p'],
    ['a', 'b', 'c'],
    ['d', 'e', 'f']
])

d_3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [17, 18, 19]
    ]
])

print(np.ndim(d_0), "\n", d_0)
print(np.ndim(d_1), "\n", d_1)
print(np.ndim(d_2), "\n", d_2)
print(np.ndim(d_3), "\n", d_3)

print(f"d_3[0,2,2] = {d_3[0,2,2]} + d_3[1,1,2] = {d_3[1,1,2]} = {d_3[0,2,2] + d_3[1,1,2]}")
d_03=d_3.reshape(9,-1)
print("reshaped",d_03)
print("d_0 size:", d_0.size)

flattened_array=d_3.flatten()
print("\n flattened array:",flattened_array.ndim)
print("size of flattend array is:",flattened_array.size)

0 
 42
1 
 [42 44 46 48]
2 
 [['1' '2' '3']
 ['t' 'u' 'p']
 ['a' 'b' 'c']
 ['d' 'e' 'f']]
3 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [17 18 19]]]
d_3[0,2,2] = 9 + d_3[1,1,2] = 15 = 24
reshaped [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 17]
 [18 19]]
d_0 size: 1

 flattened array: 1
size of flattend array is: 18


In [10]:
import pandas as pd

df = pd.read_csv("/employees_20.csv")

# Read CSV File
print(df)

    ID    Name  Age  Gender Department       City        State  Salary  \
0    1    Amit   22    Male         IT      Surat      Gujarat   35000   
1    2   Priya   24  Female         HR  Ahmedabad      Gujarat   42000   
2    3   Rahul   25    Male    Finance       Pune  Maharashtra   45000   
3    4    Neha   23  Female  Marketing     Mumbai  Maharashtra   39000   
4    5   Rohan   26    Male         IT  Bengaluru    Karnataka   50000   
5    6   Kavya   21  Female         HR      Delhi        Delhi   34000   
6    7   Arjun   27    Male    Finance     Jaipur    Rajasthan   55000   
7    8   Sneha   22  Female  Marketing      Surat      Gujarat   36000   
8    9   Vikas   24    Male         IT       Pune  Maharashtra   43000   
9   10   Pooja   23  Female         HR  Ahmedabad      Gujarat   41000   
10  11   Karan   25    Male    Finance      Delhi        Delhi   47000   
11  12    Riya   26  Female  Marketing     Mumbai  Maharashtra   52000   
12  13  Manish   21    Male         IT

In [7]:

# Display First 5 Rows
print(df.head())


   ID   Name  Age  Gender Department       City        State  Salary  \
0   1   Amit   22    Male         IT      Surat      Gujarat   35000   
1   2  Priya   24  Female         HR  Ahmedabad      Gujarat   42000   
2   3  Rahul   25    Male    Finance       Pune  Maharashtra   45000   
3   4   Neha   23  Female  Marketing     Mumbai  Maharashtra   39000   
4   5  Rohan   26    Male         IT  Bengaluru    Karnataka   50000   

   Experience(Years)            Email  
0                  1   amit@gmail.com  
1                  3  priya@gmail.com  
2                  4  rahul@gmail.com  
3                  2   neha@gmail.com  
4                  5  rohan@gmail.com  


In [8]:
# Display Last 5 Rows
print(df.tail())

   ID   Name  Age  Gender Department       City        State  Salary  \
0   1   Amit   22    Male         IT      Surat      Gujarat   35000   
1   2  Priya   24  Female         HR  Ahmedabad      Gujarat   42000   
2   3  Rahul   25    Male    Finance       Pune  Maharashtra   45000   
3   4   Neha   23  Female  Marketing     Mumbai  Maharashtra   39000   
4   5  Rohan   26    Male         IT  Bengaluru    Karnataka   50000   

   Experience(Years)            Email  
0                  1   amit@gmail.com  
1                  3  priya@gmail.com  
2                  4  rahul@gmail.com  
3                  2   neha@gmail.com  
4                  5  rohan@gmail.com  


In [29]:
# Display Shape
print(df.shape)

(20, 10)


In [30]:
# Dataset Information
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   ID                 20 non-null     int64 
 1   Name               20 non-null     object
 2   Age                20 non-null     int64 
 3   Gender             20 non-null     object
 4   Department         20 non-null     object
 5   City               20 non-null     object
 6   State              20 non-null     object
 7   Salary             20 non-null     int64 
 8   Experience(Years)  20 non-null     int64 
 9   Email              20 non-null     object
dtypes: int64(4), object(6)
memory usage: 1.7+ KB
None


In [12]:
# Statistical Summary
print(df.describe())

             ID        Age        Salary  Experience(Years)
count  20.00000  20.000000     20.000000          20.000000
mean   10.50000  23.900000  43400.000000           3.150000
std     5.91608   1.916686   7148.058257           1.631112
min     1.00000  21.000000  33000.000000           1.000000
25%     5.75000  22.000000  37750.000000           2.000000
50%    10.50000  24.000000  42500.000000           3.000000
75%    15.25000  25.250000  48500.000000           4.250000
max    20.00000  27.000000  56000.000000           6.000000


In [48]:
# Column Names
print(df.columns)

Index(['ID', 'Name', 'Age', 'Gender', 'Department', 'City', 'State', 'Salary',
       'Experience(Years)', 'Email'],
      dtype='object')


In [47]:
# Missing Values
print(df.isnull().sum())

ID                   0
Name                 0
Age                  0
Gender               0
Department           0
City                 0
State                0
Salary               0
Experience(Years)    0
Email                0
dtype: int64


In [46]:
# Sort by Age
print(df.sort_values(by="Age"))

    ID    Name  Age  Gender Department       City        State  Salary  \
5    6   Kavya   21  Female         HR      Delhi        Delhi   34000   
12  13  Manish   21    Male         IT  Bengaluru    Karnataka   33000   
7    8   Sneha   22  Female  Marketing      Surat      Gujarat   36000   
0    1    Amit   22    Male         IT      Surat      Gujarat   35000   
14  15  Sachin   22    Male    Finance      Surat      Gujarat   37000   
19  20   Komal   22  Female  Marketing     Mumbai  Maharashtra   38000   
3    4    Neha   23  Female  Marketing     Mumbai  Maharashtra   39000   
9   10   Pooja   23  Female         HR  Ahmedabad      Gujarat   41000   
17  18   Nisha   23  Female         HR  Bengaluru    Karnataka   40000   
8    9   Vikas   24    Male         IT       Pune  Maharashtra   43000   
15  16   Meera   24  Female  Marketing       Pune  Maharashtra   44000   
1    2   Priya   24  Female         HR  Ahmedabad      Gujarat   42000   
2    3   Rahul   25    Male    Finance

In [45]:
# Employees Age > 23
print(df[df["Age"] > 23])

    ID    Name  Age  Gender Department       City        State  Salary  \
1    2   Priya   24  Female         HR  Ahmedabad      Gujarat   42000   
2    3   Rahul   25    Male    Finance       Pune  Maharashtra   45000   
4    5   Rohan   26    Male         IT  Bengaluru    Karnataka   50000   
6    7   Arjun   27    Male    Finance     Jaipur    Rajasthan   55000   
8    9   Vikas   24    Male         IT       Pune  Maharashtra   43000   
10  11   Karan   25    Male    Finance      Delhi        Delhi   47000   
11  12    Riya   26  Female  Marketing     Mumbai  Maharashtra   52000   
13  14  Anjali   27  Female         HR     Jaipur    Rajasthan   56000   
15  16   Meera   24  Female  Marketing       Pune  Maharashtra   44000   
16  17  Deepak   25    Male         IT  Ahmedabad      Gujarat   48000   
18  19    Ajay   26    Male    Finance      Delhi        Delhi   53000   

    Experience(Years)             Email  
1                   3   priya@gmail.com  
2                   4   rah

In [44]:
# Employees Salary > 45000
print(df[df["Salary"] > 45000])

    ID    Name  Age  Gender Department       City        State  Salary  \
4    5   Rohan   26    Male         IT  Bengaluru    Karnataka   50000   
6    7   Arjun   27    Male    Finance     Jaipur    Rajasthan   55000   
10  11   Karan   25    Male    Finance      Delhi        Delhi   47000   
11  12    Riya   26  Female  Marketing     Mumbai  Maharashtra   52000   
13  14  Anjali   27  Female         HR     Jaipur    Rajasthan   56000   
16  17  Deepak   25    Male         IT  Ahmedabad      Gujarat   48000   
18  19    Ajay   26    Male    Finance      Delhi        Delhi   53000   

    Experience(Years)             Email  
4                   5   rohan@gmail.com  
6                   6   arjun@gmail.com  
10                  4   karan@gmail.com  
11                  5    riya@gmail.com  
13                  6  anjali@gmail.com  
16                  4  deepak@gmail.com  
18                  5    ajay@gmail.com  


In [43]:
# Mean Salary
print(df["Salary"].mean())

43400.0


In [42]:
# Maximum Salary
print(df["Salary"].max())

56000


In [41]:
# Minimum Salary
print(df["Salary"].min())

33000


In [40]:
# Average Age
print(df["Age"].mean())

23.9


In [39]:
# Count Employees
print(df["Name"].count())

20


In [38]:
# Unique Departments
print(df["Department"].unique())

['IT' 'HR' 'Finance' 'Marketing']


In [37]:
# Number of Departments
print(df["Department"].value_counts())

Department
IT           5
HR           5
Finance      5
Marketing    5
Name: count, dtype: int64


In [36]:
# Select Only Name and Salary
print(df[["Name", "Salary"]])

      Name  Salary
0     Amit   35000
1    Priya   42000
2    Rahul   45000
3     Neha   39000
4    Rohan   50000
5    Kavya   34000
6    Arjun   55000
7    Sneha   36000
8    Vikas   43000
9    Pooja   41000
10   Karan   47000
11    Riya   52000
12  Manish   33000
13  Anjali   56000
14  Sachin   37000
15   Meera   44000
16  Deepak   48000
17   Nisha   40000
18    Ajay   53000
19   Komal   38000


In [35]:
# Employees from Gujarat
print(df[df["State"] == "Gujarat"])

    ID    Name  Age  Gender Department       City    State  Salary  \
0    1    Amit   22    Male         IT      Surat  Gujarat   35000   
1    2   Priya   24  Female         HR  Ahmedabad  Gujarat   42000   
7    8   Sneha   22  Female  Marketing      Surat  Gujarat   36000   
9   10   Pooja   23  Female         HR  Ahmedabad  Gujarat   41000   
14  15  Sachin   22    Male    Finance      Surat  Gujarat   37000   
16  17  Deepak   25    Male         IT  Ahmedabad  Gujarat   48000   

    Experience(Years)             Email  
0                   1    amit@gmail.com  
1                   3   priya@gmail.com  
7                   2   sneha@gmail.com  
9                   2   pooja@gmail.com  
14                  2  sachin@gmail.com  
16                  4  deepak@gmail.com  


In [34]:
# Employees with Experience More Than 3 Years
print(df[df["Experience(Years)"] > 3])

    ID    Name  Age  Gender Department       City        State  Salary  \
2    3   Rahul   25    Male    Finance       Pune  Maharashtra   45000   
4    5   Rohan   26    Male         IT  Bengaluru    Karnataka   50000   
6    7   Arjun   27    Male    Finance     Jaipur    Rajasthan   55000   
10  11   Karan   25    Male    Finance      Delhi        Delhi   47000   
11  12    Riya   26  Female  Marketing     Mumbai  Maharashtra   52000   
13  14  Anjali   27  Female         HR     Jaipur    Rajasthan   56000   
16  17  Deepak   25    Male         IT  Ahmedabad      Gujarat   48000   
18  19    Ajay   26    Male    Finance      Delhi        Delhi   53000   

    Experience(Years)             Email  
2                   4   rahul@gmail.com  
4                   5   rohan@gmail.com  
6                   6   arjun@gmail.com  
10                  4   karan@gmail.com  
11                  5    riya@gmail.com  
13                  6  anjali@gmail.com  
16                  4  deepak@gmail.com

In [33]:
# Highest Salary Employee
print(df[df["Salary"] == df["Salary"].max()])

    ID    Name  Age  Gender Department    City      State  Salary  \
13  14  Anjali   27  Female         HR  Jaipur  Rajasthan   56000   

    Experience(Years)             Email  
13                  6  anjali@gmail.com  


In [32]:
# Lowest Salary Employee
print(df[df["Salary"] == df["Salary"].min()])

    ID    Name  Age Gender Department       City      State  Salary  \
12  13  Manish   21   Male         IT  Bengaluru  Karnataka   33000   

    Experience(Years)             Email  
12                  1  manish@gmail.com  


In [31]:
# Save Updated CSV
df.to_csv("new_employees.csv", index=False)

print("CSV Saved Successfully")

CSV Saved Successfully
