<a href="https://colab.research.google.com/github/cse240840131002-ship-it/practice/blob/main/Day_2(08_07_26).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list_1=[]
for i in range(10):
  list_1.append(i)
  list_1.append(i+1)
print(list_1)
print(list_1[1])

[0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10]
1


In [ ]:
n=int(input("enter the number:"))
for i in range(2,7):
  print(i*n)

enter the number:2
4
6
8
10
12


In [ ]:
count=0
while count<5:
  print(count)
  count+=1

0
1
2
3
4


In [ ]:
user_input=''
while user_input .lower() != 'quit' :
  user_input=input("enter something to stop:")
print("you entered:",user_input)

enter something to stop:quite
enter something to stop:6
enter something to stop:8
enter something to stop:quit
you entered: quit


In [ ]:
def greet():
  print("hello world")
greet()

hello world


In [ ]:
def find_square(num):
  result=num*num
  return result
square=find_square(5)
print("Square :-",square)

Square :- 25


In [ ]:
def sum_of_digits(n):
    total = 0

    while n > 0:
        digit = n % 10
        total = total + digit
        n = n // 10

    return total


num = int(input("Enter a number: "))
print("Sum of digits =", sum_of_digits(num))

Enter a number: 123
Sum of digits = 6


In [ ]:
square = lambda x: x * x
print(square(5))
#Map
number=[2,3,4,5]
mul=list(map(lambda x:x*2,number))
print("map method:-",mul)




25
map method:- [4, 6, 8, 10]


In [ ]:
print(filter)
print(type(filter))
del filter


[2, 4, 6, 8, 10]
<class 'list'>


In [ ]:
print(filter)
print(type(filter))


<class 'filter'>
<class 'type'>


In [ ]:
numbers = [2, 3, 4, 5, 6, 7, 8, 9, 10]

even_numbers = list(filter(lambda x: x % 2 == 0, numbers))

print(even_numbers)

[2, 4, 6, 8, 10]


In [ ]:
import numpy as np

d_0 = np.array(42)

d_1 = np.array([42, 44, 46, 48])

d_2 = np.array([
    [1, 2, 3],
    ['t', 'u', 'p'],
    ['a', 'b', 'c'],
    ['d', 'e', 'f']
])

d_3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [17, 18, 19]
    ]
])

print(np.ndim(d_0), "\n", d_0)
print(np.ndim(d_1), "\n", d_1)
print(np.ndim(d_2), "\n", d_2)
print(np.ndim(d_3), "\n", d_3)

print(f"d_3[0,2,2] = {d_3[0,2,2]} + d_3[1,1,2] = {d_3[1,1,2]} = {d_3[0,2,2] + d_3[1,1,2]}")
d_03=d_3.reshape(9,-1)
print("reshaped",d_03)
print("d_0 size:", d_0.size)

flattened_array=d_3.flatten()
print("\n flattened array:",flattened_array.ndim)
print("size of flattend array is:",flattened_array.size)

0 
 42
1 
 [42 44 46 48]
2 
 [['1' '2' '3']
 ['t' 'u' 'p']
 ['a' 'b' 'c']
 ['d' 'e' 'f']]
3 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [17 18 19]]]
d_3[0,2,2] = 9 + d_3[1,1,2] = 15 = 24
reshaped [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 17]
 [18 19]]
d_0 size: 1

 flattened array: 1
size of flattend array is: 18


In [3]:
import pandas as pd

# Read CSV file
df = pd.read_csv("/content/employees_100.csv")

print(df)

     ID         Name  Age  Gender  Department       City        State  Salary  \
0     1    Employee1   21    Male         CSE  Ahmedabad      Gujarat   40350   
1     2    Employee2   22  Female          IT      Surat      Gujarat   40700   
2     3    Employee3   23    Male          AI       Pune  Maharashtra   41050   
3     4    Employee4   24  Female         ECE      Delhi        Delhi   41400   
4     5    Employee5   25    Male  Mechanical  Bengaluru    Karnataka   41750   
..  ...          ...  ...     ...         ...        ...          ...     ...   
95   96   Employee96   20  Female         CSE  Ahmedabad      Gujarat   73600   
96   97   Employee97   21    Male          IT      Surat      Gujarat   73950   
97   98   Employee98   22  Female          AI       Pune  Maharashtra   74300   
98   99   Employee99   23    Male         ECE      Delhi        Delhi   74650   
99  100  Employee100   24  Female  Mechanical  Bengaluru    Karnataka   75000   

    Experience(Years)      

In [4]:
print("1. Head")
print(df.head())

1. Head
   ID       Name  Age  Gender  Department       City        State  Salary  \
0   1  Employee1   21    Male         CSE  Ahmedabad      Gujarat   40350   
1   2  Employee2   22  Female          IT      Surat      Gujarat   40700   
2   3  Employee3   23    Male          AI       Pune  Maharashtra   41050   
3   4  Employee4   24  Female         ECE      Delhi        Delhi   41400   
4   5  Employee5   25    Male  Mechanical  Bengaluru    Karnataka   41750   

   Experience(Years)                  Email  
0                  2  employee1@example.com  
1                  3  employee2@example.com  
2                  4  employee3@example.com  
3                  5  employee4@example.com  
4                  6  employee5@example.com  


In [5]:
# 2. Display last 5 rows
print("\n2. Tail")
print(df.tail())



2. Tail
     ID         Name  Age  Gender  Department       City        State  Salary  \
95   96   Employee96   20  Female         CSE  Ahmedabad      Gujarat   73600   
96   97   Employee97   21    Male          IT      Surat      Gujarat   73950   
97   98   Employee98   22  Female          AI       Pune  Maharashtra   74300   
98   99   Employee99   23    Male         ECE      Delhi        Delhi   74650   
99  100  Employee100   24  Female  Mechanical  Bengaluru    Karnataka   75000   

    Experience(Years)                    Email  
95                  6   employee96@example.com  
96                  7   employee97@example.com  
97                  1   employee98@example.com  
98                  2   employee99@example.com  
99                  3  employee100@example.com  


In [6]:
# 3. Shape of dataset
print("\n3. Shape")
print(df.shape)



3. Shape
(100, 10)


In [7]:
# 4. Information about dataset
print("\n4. Info")
print(df.info())


4. Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   ID                 100 non-null    int64 
 1   Name               100 non-null    object
 2   Age                100 non-null    int64 
 3   Gender             100 non-null    object
 4   Department         100 non-null    object
 5   City               100 non-null    object
 6   State              100 non-null    object
 7   Salary             100 non-null    int64 
 8   Experience(Years)  100 non-null    int64 
 9   Email              100 non-null    object
dtypes: int64(4), object(6)
memory usage: 7.9+ KB
None


In [8]:
# 5. Statistical summary
print("\n5. Describe")
print(df.describe())


5. Describe
               ID         Age        Salary  Experience(Years)
count  100.000000  100.000000    100.000000         100.000000
mean    50.500000   23.460000  57675.000000           3.970000
std     29.011492    2.276006  10154.022192           2.002297
min      1.000000   20.000000  40350.000000           1.000000
25%     25.750000   21.750000  49012.500000           2.000000
50%     50.500000   23.000000  57675.000000           4.000000
75%     75.250000   25.000000  66337.500000           6.000000
max    100.000000   27.000000  75000.000000           7.000000


In [9]:
# 6. Column names
print("\n6. Columns")
print(df.columns)


6. Columns
Index(['ID', 'Name', 'Age', 'Gender', 'Department', 'City', 'State', 'Salary',
       'Experience(Years)', 'Email'],
      dtype='object')


In [10]:
# 7. Check missing values
print("\n7. Missing Values")
print(df.isnull().sum())


7. Missing Values
ID                   0
Name                 0
Age                  0
Gender               0
Department           0
City                 0
State                0
Salary               0
Experience(Years)    0
Email                0
dtype: int64


In [11]:
# 8. Sort data by Age
print("\n8. Sorted by Age")
print(df.sort_values(by="Age"))



8. Sorted by Age
    ID        Name  Age  Gender  Department       City        State  Salary  \
7    8   Employee8   20  Female          AI       Pune  Maharashtra   42800   
15  16  Employee16   20  Female         CSE  Ahmedabad      Gujarat   45600   
31  32  Employee32   20  Female          IT      Surat      Gujarat   51200   
23  24  Employee24   20  Female         ECE      Delhi        Delhi   48400   
55  56  Employee56   20  Female         CSE  Ahmedabad      Gujarat   59600   
..  ..         ...  ...     ...         ...        ...          ...     ...   
30  31  Employee31   27    Male         CSE  Ahmedabad      Gujarat   50850   
94  95  Employee95   27    Male  Mechanical  Bengaluru    Karnataka   73250   
86  87  Employee87   27    Male          IT      Surat      Gujarat   70450   
70  71  Employee71   27    Male         CSE  Ahmedabad      Gujarat   64850   
78  79  Employee79   27    Male         ECE      Delhi        Delhi   67650   

    Experience(Years)            

In [12]:
# 9. Filter students with Age > 20
print("\n9. Students Age > 20")
print(df[df["Age"] > 20])



9. Students Age > 20
     ID         Name  Age  Gender  Department       City        State  Salary  \
0     1    Employee1   21    Male         CSE  Ahmedabad      Gujarat   40350   
1     2    Employee2   22  Female          IT      Surat      Gujarat   40700   
2     3    Employee3   23    Male          AI       Pune  Maharashtra   41050   
3     4    Employee4   24  Female         ECE      Delhi        Delhi   41400   
4     5    Employee5   25    Male  Mechanical  Bengaluru    Karnataka   41750   
..  ...          ...  ...     ...         ...        ...          ...     ...   
94   95   Employee95   27    Male  Mechanical  Bengaluru    Karnataka   73250   
96   97   Employee97   21    Male          IT      Surat      Gujarat   73950   
97   98   Employee98   22  Female          AI       Pune  Maharashtra   74300   
98   99   Employee99   23    Male         ECE      Delhi        Delhi   74650   
99  100  Employee100   24  Female  Mechanical  Bengaluru    Karnataka   75000   

    E

In [13]:
# 10. Mean Age
print("\n10. Mean Age")
print(df["Age"].mean())


10. Mean Age
23.46
